[package]
name = "giwifi-gear-rs"
version = "0.1.0"
authors = ["icepie <icepie.dev@gmail.com>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }