[package]
name = "giwifi-mix-crypto"
version = "0.1.0"
authors = ["icepie <icepie.dev@gmail.com>"]

[dependencies]
getopts = "0.2"
aes = "0.6.0"
block-modes = "0.7.0"
base64 = "0.13.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'